resources:
  - ../../base

nameSuffix: -v2

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: monitor

  - path: service-patch.yaml
    target:
      kind: Service
      name: monitor
